export default function TermsPage() {
  return (
    <div className="min-h-screen" style={{ background: "var(--app-page-bg, #050c18)", color: "var(--app-text, #e2e8f0)" }}>
      <div className="max-w-3xl mx-auto px-6 py-12 md:py-16">
        <h1 className="text-2xl md:text-3xl font-bold tracking-tight uppercase mb-2" style={{ color: "#f8fafc" }}>
          Terms of Service
        </h1>
        <p className="text-xs pwc-font-mono uppercase tracking-wider mb-8" style={{ color: "#4ECCA3", opacity: 0.7 }}>
          Effective Date: June 1, 2026 &nbsp;|&nbsp; Last Updated: June 1, 2026
        </p>

        <div className="space-y-6 text-sm leading-relaxed" style={{ color: "#cbd5e1" }}>
          <div className="text-xs pwc-font-mono uppercase tracking-wider mb-4" style={{ color: "var(--app-text-muted)" }}>
            Company: Kaleon LLC &nbsp;|&nbsp; Platform: Kaleon &nbsp;|&nbsp; Governing Law: State of California
          </div>

          <Section title="Acceptance of Terms">
            <p>
              Welcome to Kaleon, an educational planning platform operated by Kaleon LLC, a California
              limited liability company. These Terms of Service ("Terms") constitute a legally binding
              agreement between you ("User," "you," or "your") and Kaleon LLC ("Kaleon," "we," "us," or
              "our") governing your access to and use of the Kaleon platform, website, applications, and
              related services (collectively, the "Services").
            </p>
            <div className="p-3 rounded text-xs font-bold uppercase tracking-wider mt-2" style={{ background: "rgba(78,204,163,0.1)", color: "#4ECCA3", border: "1px solid rgba(78,204,163,0.2)" }}>
              BY CREATING AN ACCOUNT, ACCESSING, OR USING THE SERVICES, YOU ACKNOWLEDGE THAT
              YOU HAVE READ, UNDERSTOOD, AND AGREE TO BE BOUND BY THESE TERMS AND OUR
              PRIVACY POLICY, WHICH IS INCORPORATED HEREIN BY REFERENCE. IF YOU DO NOT AGREE
              TO THESE TERMS, YOU MUST NOT ACCESS OR USE THE SERVICES.
            </div>
          </Section>

          <Section title="1. Definitions">
            <DefItem term="1.1 Account" def="The registered user profile created by you to access and use the Services." />
            <DefItem term="1.2 Educational Records" def="Academic transcripts, course histories, grade point averages, transfer credit evaluations, and other educational information you upload or submit to the Services." />
            <DefItem term="1.3 Services" def="The Kaleon educational planning platform, including all features, tools, AI-powered recommendations, course planning functionality, transfer readiness assessments, and related services." />
            <DefItem term="1.4 User Content" def="Any content, data, information, or materials you upload, submit, post, or otherwise provide through the Services, including Educational Records." />
            <DefItem term="1.5 Personalized Pathway" def="AI/ML-generated educational planning outputs, recommendations, course sequences, and transfer readiness analyses generated by the Services based on your User Content." />
            <DefItem term="1.6 Counselor" def="An independent educational advisor who accesses the Services as an independent user and with whom you have voluntarily chosen to share your information." />
            <DefItem term="1.7 Third-Party Services" def="External platforms, APIs, and service providers integrated with or used to power the Services." />
            <DefItem term="1.8 Beta Services" def="Features or functionality designated as 'beta,' 'preview,' 'experimental,' or similar." />
            <DefItem term="1.9 Intellectual Property Rights" def="All patent rights, copyright rights, trademark rights, trade secret rights, and other intellectual property or proprietary rights." />
          </Section>

          <Section title="2. About Kaleon">
            <p>
              Kaleon is an educational planning platform designed to help community college students,
              transfer students, and other learners better understand academic progress, transfer readiness,
              course planning options, and educational opportunities. Kaleon uses artificial intelligence
              and machine learning to generate personalized educational pathway recommendations based on
              information provided by users.
            </p>
            <p className="mt-2">
              Kaleon does not provide legal, financial, academic admissions, or professional advising
              services. Kaleon is not a licensed academic counselor, educational institution, or accredited
              advising organization. All recommendations generated by the Services are informational only.
            </p>
          </Section>

          <Section title="3. Eligibility">
            <p>To use the Services, you must meet the following requirements:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li>Be at least 13 years of age (users 13&ndash;17 must review Terms with a parent or guardian)</li>
              <li>Have the legal capacity to enter into a binding contract</li>
              <li>Be authorized to submit any information or Educational Records you provide</li>
              <li>Comply with all applicable laws and regulations</li>
              <li>Provide accurate information to the best of your knowledge</li>
            </ul>
          </Section>

          <Section title="4. Account Registration and Security">
            <p>To access the Services, you must create an Account with accurate information. You are solely
            responsible for maintaining the confidentiality of your login credentials and for all activities
            that occur under your Account. You may not create more than one Account.</p>
          </Section>

          <Section title="5. License and Restrictions">
            <p>
              Subject to your compliance, Kaleon grants you a limited, non-exclusive, non-transferable,
              revocable license to access and use the Services for personal, non-commercial educational
              planning purposes.
            </p>
            <p className="mt-2">You may not:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li>Copy, modify, or create derivative works based on the Services</li>
              <li>Reverse engineer, decompile, or attempt to derive source code</li>
              <li>Rent, lease, sell, or transfer access to the Services</li>
              <li>Use the Services to build a competitive product</li>
              <li>Use automated tools, bots, or scrapers without express permission</li>
            </ul>
          </Section>

          <Section title="6. User Content and Educational Records">
            <p>You retain all ownership rights in your User Content. By submitting User Content, you grant
            Kaleon a limited license to use, process, store, and analyze your content solely to provide
            and improve the Services.</p>
            <p className="mt-2">
              You may not upload content that infringes third-party rights, contains sensitive financial
              information, or violates applicable law.
            </p>
          </Section>

          <Section title="7. Transcript Uploads">
            <p>
              By uploading a transcript, you represent that it belongs to you and that the information is
              accurate. You must not upload documents containing Social Security numbers, bank or credit
              card information, tax records, or medical records.
            </p>
          </Section>

          <Section title="8. AI-Powered Features and Personalized Pathways">
            <p>
              Kaleon uses AI/ML technologies to analyze your User Content and generate Personalized
              Pathways. All AI-generated outputs are for informational purposes only and are not a substitute
              for advice from a licensed academic counselor. You are strongly advised to verify all
              AI-generated recommendations with your institution before making academic decisions.
            </p>
            <p className="mt-2">
              Kaleon does not use AI/ML systems to build student profiles for commercial purposes or
              targeted advertising.
            </p>
          </Section>

          <Section title="9. Third-Party Integrations">
            <p>
              The Services integrate with several third-party providers including Anthropic (Claude), OpenAI,
              Perplexity AI, Assist.org, Google Analytics, and Cloudflare. Your use of these services is
              subject to their respective terms and privacy policies. Kaleon uses commercially reasonable
              efforts to minimize personal data shared with these providers.
            </p>
          </Section>

          <Section title="10. Educational Planning Disclaimer">
            <p>
              ALL RECOMMENDATIONS ARE INFORMATIONAL ONLY AND DO NOT CONSTITUTE ACADEMIC
              ADVISING. Students must verify course selections, transfer requirements, and degree
              requirements with their educational institution before acting on any recommendation.
            </p>
          </Section>

          <Section title="11. Counselor Access Features">
            <p>
              Students may voluntarily share their information with Counselors. Counselors are independent
              users who operate independently of Kaleon. Kaleon has no control over advice provided by
              Counselors. Students may revoke Counselor access at any time.
            </p>
          </Section>

          <Section title="12. Beta Software Disclaimer">
            <p>
              Kaleon is currently offered as a beta platform. The Services are experimental and may contain
              bugs, errors, or defects. Beta Services are provided "AS IS" and "AS AVAILABLE" without
              warranties of any kind. Your use of Beta Services is entirely at your own risk.
            </p>
          </Section>

          <Section title="13. Acceptable Use Policy">
            <p>You agree not to engage in prohibited activities including:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li>Illegal activities or violation of applicable law</li>
              <li>Misrepresentation of identity or academic records</li>
              <li>Uploading viruses, malware, or harmful code</li>
              <li>Attempting to bypass security measures</li>
              <li>Infringing intellectual property rights</li>
              <li>Harassment or discriminatory conduct</li>
            </ul>
          </Section>

          <Section title="14. Intellectual Property">
            <p>
              The Services, including all software, algorithms, AI/ML models, branding, and content, are
              owned by Kaleon LLC and are protected by intellectual property laws. "Kaleon" and the Kaleon
              logo are trademarks of Kaleon LLC.
            </p>
          </Section>

          <Section title="15. Data Privacy and Regulatory Compliance">
            <p>
              Kaleon is committed to protecting your data in compliance with applicable laws including
              FERPA, CCPA/CPRA, SOPIPA, and COPPA. Kaleon does not sell personal information, does not
              use your data for targeted advertising, and implements commercially reasonable security
              measures.
            </p>
          </Section>

          <Section title="16. Data Retention and Deletion">
            <p>
              Kaleon retains your data for as long as your Account is active. You may request Account
              deletion at any time. Kaleon will process verified deletion requests within 30 days. You
              may request a copy of your personal data prior to deletion.
            </p>
          </Section>

          <Section title="17. No Guarantee of Educational Outcomes">
            <p>
              Kaleon does not guarantee admission to any institution, transfer acceptance, degree
              completion, scholarship awards, academic success, or any specific educational outcome.
              Educational outcomes depend on numerous factors outside Kaleon's control.
            </p>
          </Section>

          <Section title="18. Service Availability">
            <p>
              Kaleon does not guarantee uninterrupted, error-free, or secure access to the Services. Kaleon
              reserves the right to modify, suspend, or discontinue any portion of the Services at any
              time with or without notice.
            </p>
          </Section>

          <Section title="19. Disclaimer of Warranties">
            <p>
              THE SERVICES ARE PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND.
              KALEON EXPRESSLY DISCLAIMS ALL IMPLIED WARRANTIES, INCLUDING MERCHANTABILITY AND
              FITNESS FOR A PARTICULAR PURPOSE.
            </p>
          </Section>

          <Section title="20. Limitation of Liability">
            <p>
              KALEON'S TOTAL LIABILITY SHALL NOT EXCEED $100.00. KALEON SHALL NOT BE LIABLE FOR
              INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES.
            </p>
          </Section>

          <Section title="21. Indemnification">
            <p>
              You agree to defend, indemnify, and hold harmless Kaleon and Kaleon LLC from claims arising
              out of your use of the Services, your User Content, or your violation of these Terms.
            </p>
          </Section>

          <Section title="22. Dispute Resolution and Arbitration">
            <p>
              Before initiating formal proceedings, you agree to attempt informal resolution by contacting
              Kaleon. Any unresolved dispute shall be resolved by final and binding individual arbitration
              conducted by the American Arbitration Association. You and Kaleon agree to a class action
              waiver. You have the right to opt out of arbitration within 30 days of first accepting
              these Terms.
            </p>
          </Section>

          <Section title="23. DMCA Copyright Policy">
            <p>
              If you believe content available through the Services infringes your copyright, please submit
              a notification to Kaleon's designated DMCA Agent at support@kaleon.org.
            </p>
          </Section>

          <Section title="24. Changes to These Terms">
            <p>
              Kaleon may update these Terms periodically. Your continued use of the Services after the
              effective date of any updated Terms constitutes your acceptance of the revised Terms.
            </p>
          </Section>

          <Section title="25. Governing Law and Jurisdiction">
            <p>
              These Terms shall be governed by the laws of the State of California. For any disputes not
              subject to arbitration, the parties consent to the exclusive jurisdiction of courts located
              in California.
            </p>
          </Section>

          <Section title="26. Contact Information">
            <div className="mt-2 space-y-1" style={{ color: "#4ECCA3" }}>
              <p>Company: Kaleon LLC</p>
              <p>Platform: Kaleon</p>
              <p>Email: <a href="mailto:support@kaleon.org" className="underline hover:no-underline">support@kaleon.org</a></p>
              <p>Location: California, United States</p>
            </div>
          </Section>

          <div className="pt-4 border-t" style={{ borderColor: "rgba(78,204,163,0.15)" }}>
            <p className="text-xs" style={{ color: "var(--app-text-muted)" }}>
              These Terms, together with the Privacy Policy, constitute the entire agreement between you
              and Kaleon with respect to the Services.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <h2 className="text-base font-bold tracking-tight mb-3 mt-8" style={{ color: "#f8fafc" }}>
        {title}
      </h2>
      <div className="space-y-3">{children}</div>
    </section>
  );
}

function DefItem({ term, def }: { term: string; def: string }) {
  return (
    <div className="mt-3">
      <h3 className="text-sm font-semibold" style={{ color: "#e2e8f0" }}>{term}</h3>
      <p className="mt-1">{def}</p>
    </div>
  );
}
