import { useEffect, useState } from "react";
import { useParams, useLocation } from "wouter";
import Nav from "@/components/nav";
import { Button } from "@/components/ui/button";
import { useToast } from "@/hooks/use-toast";
import { ArrowLeft, Download, Loader2, BookOpen, AlertTriangle } from "lucide-react";
import ReactMarkdown from "react-markdown";

interface Guidebook {
  id: number;
  title?: string;
  contentMarkdown?: string;
  profileId?: number;
  createdAt?: string;
}

export default function Guidebook() {
  const { guidebookId } = useParams<{ guidebookId: string }>();
  const [, navigate] = useLocation();
  const { toast } = useToast();
  const [guidebook, setGuidebook] = useState<Guidebook | null>(null);
  const [loading, setLoading] = useState(true);
  const gid = parseInt(guidebookId);

  useEffect(() => {
    fetch(`/api/guidebooks/${gid}`, { credentials: "include" })
      .then(r => r.json())
      .then((g: Guidebook) => setGuidebook(g))
      .catch(() => toast({ title: "Error loading guidebook", variant: "destructive" }))
      .finally(() => setLoading(false));
  }, [gid]);

  const downloadMarkdown = () => {
    if (!guidebook?.contentMarkdown) return;
    const blob = new Blob([guidebook.contentMarkdown], { type: "text/markdown;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `pathwise-guidebook-${guidebook.id}.md`;
    a.click();
    URL.revokeObjectURL(url);
    toast({ title: "Guidebook downloaded!" });
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-slate-50 flex items-center justify-center">
        <div className="flex flex-col items-center gap-3">
          <Loader2 className="h-8 w-8 animate-spin text-indigo-600" />
          <p className="text-sm text-slate-500">Loading your guidebook…</p>
        </div>
      </div>
    );
  }

  if (!guidebook) {
    return (
      <div className="min-h-screen bg-slate-50 flex items-center justify-center">
        <div className="text-center">
          <BookOpen className="h-12 w-12 text-slate-300 mx-auto mb-3" />
          <p className="text-slate-500">Guidebook not found.</p>
          <Button variant="outline" onClick={() => navigate(-1)} className="mt-4">Go Back</Button>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-slate-50">
      <Nav profileId={guidebook.profileId} />
      <main className="pt-14 px-4 md:px-8 max-w-4xl mx-auto">
        {/* Header */}
        <div className="py-8 flex items-start justify-between gap-4">
          <div>
            <button onClick={() => navigate(-1)} className="flex items-center gap-1 text-sm text-slate-500 hover:text-slate-700 mb-3">
              <ArrowLeft className="h-4 w-4" /> Back to Pathways
            </button>
            <h1 className="text-2xl font-bold text-slate-900">{guidebook.title ?? "Your Transfer Guidebook"}</h1>
            {guidebook.createdAt && (
              <p className="text-xs text-slate-400 mt-1">
                Generated {new Date(guidebook.createdAt).toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}
              </p>
            )}
          </div>
          <Button onClick={downloadMarkdown} variant="outline" className="flex-shrink-0">
            <Download className="h-4 w-4 mr-2" /> Download .md
          </Button>
        </div>

        {/* Disclaimer banner */}
        <div className="bg-amber-50 border border-amber-200 rounded-lg p-3 mb-6 flex gap-2">
          <AlertTriangle className="h-4 w-4 text-amber-500 flex-shrink-0 mt-0.5" />
          <p className="text-xs text-amber-700">
            This guidebook was generated by AI and is not a substitute for official academic advising.
            Verify all requirements with your community college counselor and each university's official transfer admissions page.
            Data shown is estimated as of early 2025 and may have changed.
          </p>
        </div>

        {/* Guidebook content */}
        <div className="bg-white border border-slate-200 rounded-xl p-6 md:p-10 mb-12 prose prose-slate prose-sm md:prose-base max-w-none">
          <ReactMarkdown
            components={{
              h1: ({ children }) => <h1 className="text-2xl font-bold text-slate-900 mb-4 border-b pb-2">{children}</h1>,
              h2: ({ children }) => <h2 className="text-xl font-bold text-indigo-800 mt-8 mb-3">{children}</h2>,
              h3: ({ children }) => <h3 className="text-base font-semibold text-slate-800 mt-5 mb-2">{children}</h3>,
              h4: ({ children }) => <h4 className="text-sm font-semibold text-slate-700 mt-4 mb-1">{children}</h4>,
              blockquote: ({ children }) => (
                <blockquote className="border-l-4 border-amber-400 bg-amber-50 pl-4 pr-3 py-2 my-4 rounded-r-lg text-amber-800 text-sm not-italic">
                  {children}
                </blockquote>
              ),
              table: ({ children }) => (
                <div className="overflow-x-auto my-4">
                  <table className="min-w-full border border-slate-200 rounded-lg overflow-hidden text-sm">
                    {children}
                  </table>
                </div>
              ),
              th: ({ children }) => <th className="bg-slate-100 px-3 py-2 text-left font-semibold text-slate-700 border-b border-slate-200">{children}</th>,
              td: ({ children }) => <td className="px-3 py-2 border-b border-slate-100 text-slate-600">{children}</td>,
              ul: ({ children }) => <ul className="list-disc list-inside space-y-1 text-slate-600">{children}</ul>,
              ol: ({ children }) => <ol className="list-decimal list-inside space-y-1 text-slate-600">{children}</ol>,
              li: ({ children }) => <li className="text-sm">{children}</li>,
              strong: ({ children }) => <strong className="font-semibold text-slate-800">{children}</strong>,
              a: ({ href, children }) => (
                <a href={href} target="_blank" rel="noopener noreferrer" className="text-indigo-600 hover:underline">
                  {children}
                </a>
              ),
              p: ({ children }) => <p className="text-slate-600 leading-relaxed mb-3">{children}</p>,
              hr: () => <hr className="border-slate-200 my-6" />,
            }}
          >
            {guidebook.contentMarkdown ?? "No content available."}
          </ReactMarkdown>
        </div>
      </main>
    </div>
  );
}
