import { useState, useCallback } from "react";
import { useLocation } from "wouter";
import { motion } from "framer-motion";
import { Checkbox } from "@/components/ui/checkbox";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from "@/components/ui/dialog";
import { useAuth } from "@/contexts/auth-context";
import { t } from "@/lib/copy";

const AUTH_BYPASS = import.meta.env.VITE_AUTH_BYPASS === "true";

const AGREEMENT_TEXT = `Kaleon Beta Participation Agreement

Effective Date: 06/01/2026

Thank you for participating in the Kaleon Beta Program.

By accessing or using Kaleon's beta services, you acknowledge and agree to the following terms.

1. Purpose of the Beta Program

Kaleon is currently testing and improving its educational planning platform. The purpose of the beta program is to:
• Identify bugs and technical issues
• Improve recommendations and user experience
• Evaluate platform functionality
• Gather user feedback
• Refine future product features

Your participation helps shape the future development of Kaleon.

2. Beta Status

You understand that Kaleon is currently in beta. As a beta participant, you acknowledge that:
• Features may change without notice
• Certain functionality may be incomplete
• Errors or inaccuracies may occur
• Service interruptions may occur
• Recommendations may not always be accurate or complete

Kaleon is actively improving the platform throughout the beta period.

3. Educational Recommendations

Kaleon provides informational educational planning tools and recommendations. Recommendations generated by Kaleon may include:
• Course planning suggestions
• Transfer readiness assessments
• Academic progress summaries
• Educational pathway recommendations

These recommendations are informational only. You agree to verify important academic decisions with your institution, counselor, academic advisor, or other qualified educational professional before taking action. Kaleon is not a substitute for official academic advising.

4. Information You Provide

By participating in the beta program, you represent that:
• Information you submit is accurate to the best of your knowledge
• Any transcript or academic record you upload belongs to you or you are authorized to provide it
• You have reviewed Kaleon's Privacy Policy and Terms of Service

5. Feedback and Product Improvement

As a beta participant, you may be invited to provide surveys, feedback forms, bug reports, product suggestions, and user experience feedback. Participation in feedback activities is voluntary. Kaleon may use feedback submitted during the beta program to improve the platform and future services.

6. Data Collection During Beta

During the beta program, Kaleon may collect information regarding platform usage, feature engagement, performance metrics, feedback submissions, and bug reports. This information helps improve platform functionality and user experience. Information is handled in accordance with Kaleon's Privacy Policy.

7. No Guarantee of Outcomes

Participation in the beta program does not guarantee transfer admission, academic success, degree completion, scholarship awards, financial aid eligibility, or graduation timelines. Educational outcomes depend on many factors outside Kaleon's control.

8. Service Availability

Because Kaleon is in beta, services may be modified, suspended, interrupted, or discontinued at any time. Kaleon is not responsible for losses resulting from temporary service interruptions, feature changes, or platform maintenance.

9. Voluntary Participation

Participation in the beta program is voluntary. You may stop using Kaleon at any time. You may also request deletion of your account and associated information in accordance with Kaleon's Privacy Policy.

10. Updates to the Beta Program

Kaleon may modify the beta program, features, participation requirements, or related policies as development continues. Material changes may be communicated through the platform or by email.

11. Acceptance

By selecting "I Agree" or by continuing to use Kaleon's beta services, you acknowledge that:
• You understand that Kaleon is a beta product
• You understand that features and recommendations may change
• You understand that recommendations are informational only
• You agree to participate under the terms described in this agreement
• You have reviewed Kaleon's Privacy Policy and Terms of Service`;

export default function BetaAgreementModal({
  open,
  onOpenChange,
}: {
  open: boolean;
  onOpenChange: (open: boolean) => void;
}) {
  const [, navigate] = useLocation();
  const { isAuthenticated } = useAuth();
  const [scrolledToBottom, setScrolledToBottom] = useState(false);
  const [agreed, setAgreed] = useState(false);

  const handleScroll = useCallback(
    (e: React.UIEvent<HTMLDivElement>) => {
      const el = e.currentTarget;
      const threshold = 5; // px from bottom
      const atBottom =
        el.scrollHeight - el.scrollTop - el.clientHeight < threshold;
      if (atBottom && !scrolledToBottom) {
        setScrolledToBottom(true);
      }
    },
    [scrolledToBottom]
  );

  const handleAgree = useCallback(() => {
    if (!agreed) return;
    onOpenChange(false);

    // Match the original startOnboarding behavior
    if (AUTH_BYPASS || isAuthenticated) {
      navigate("/onboarding");
      return;
    }
    navigate("/auth?mode=signup&returnTo=/onboarding");
  }, [agreed, navigate, onOpenChange, isAuthenticated]);

  const handleDecline = useCallback(() => {
    setAgreed(false);
    setScrolledToBottom(false);
    onOpenChange(false);
  }, [onOpenChange]);

  const handleCheckboxChange = useCallback((checked: boolean) => {
    setAgreed(checked);
  }, []);

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent
        className="sm:max-w-xl p-0 flex flex-col gap-0 overflow-hidden"
        style={{
          background: "#0a1628",
          border: "1px solid rgba(78,204,163,0.2)",
          color: "#e2e8f0",
          height: "90vh",
          maxHeight: "600px",
        }}
      >
        <DialogHeader className="p-6 pb-2 shrink-0">
          <DialogTitle
            className="text-lg font-bold uppercase tracking-tight"
            style={{ color: "#f8fafc" }}
          >
            Beta Participation Agreement
          </DialogTitle>
          <DialogDescription
            className="text-xs pwc-font-mono uppercase tracking-wider"
            style={{ color: "#4ECCA3", opacity: 0.7 }}
          >
            Effective Date: 06/01/2026
          </DialogDescription>
        </DialogHeader>

        {/* Scrollable agreement content */}
        <div className="px-6 overflow-hidden min-h-0 flex-1">
          <div
            className="h-full overflow-y-auto pr-4 text-sm leading-relaxed whitespace-pre-line scrollbar-custom focus:outline-none focus:ring-2 focus:ring-[#4ECCA3] focus:ring-inset"
            style={{ color: "#cbd5e1" }}
            onScroll={handleScroll}
            tabIndex={0}
            role="region"
            aria-label="Beta participation agreement text"
          >
            {AGREEMENT_TEXT}
          </div>
        </div>

        {/* Progress indicator / scroll prompt */}
        {!scrolledToBottom && (
          <motion.p
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            className="text-xs text-center px-6 py-1.5 pwc-font-mono uppercase tracking-wider shrink-0"
            style={{ color: "#4ECCA3", opacity: 0.6 }}
          >
            ↓ Scroll to the bottom to continue
          </motion.p>
        )}

        {/* Checkbox + action buttons */}
        <div
          className="p-6 pt-4 flex flex-col gap-4 shrink-0"
          style={{
            borderTop: "1px solid rgba(78,204,163,0.1)",
          }}
        >
          {/* Checkbox */}
          <div className="flex items-start gap-3">
            <Checkbox
              id="beta-agree"
              checked={agreed}
              disabled={!scrolledToBottom}
              onCheckedChange={handleCheckboxChange}
              className="mt-0.5 shrink-0"
              style={{
                borderColor: scrolledToBottom
                  ? "rgba(78,204,163,0.5)"
                  : "rgba(100,116,139,0.4)",
              }}
            />
            <label
              htmlFor="beta-agree"
              className="text-xs leading-relaxed select-none cursor-pointer"
              style={{
                color: scrolledToBottom ? "#cbd5e1" : "var(--app-text-muted)",
              }}
            >
              I have read and agree to the{" "}
              <strong style={{ color: "#4ECCA3" }}>Beta Participation Agreement</strong>. I also
              acknowledge that I have reviewed{" "}
              <a
                href="/privacy"
                target="_blank"
                rel="noopener noreferrer"
                className="underline underline-offset-2 hover:no-underline"
                style={{ color: "#4ECCA3" }}
              >
                Privacy Policy
              </a>{" "}
              and{" "}
              <a
                href="/terms"
                target="_blank"
                rel="noopener noreferrer"
                className="underline underline-offset-2 hover:no-underline"
                style={{ color: "#4ECCA3" }}
              >
                Terms of Service
              </a>.
            </label>
          </div>

          {/* Buttons */}
          <div className="flex gap-3">
            <button
              onClick={handleDecline}
              className="flex-1 px-4 py-2.5 text-sm pwc-font-mono uppercase tracking-wider font-bold"
              style={{
                borderRadius: 6,
                background: "rgba(100,116,139,0.15)",
                border: "1px solid rgba(100,116,139,0.3)",
                color: "#94a3b8",
              }}
            >
              Decline
            </button>
            <button
              onClick={handleAgree}
              disabled={!agreed}
              className="flex-1 px-4 py-2.5 text-sm pwc-font-mono uppercase tracking-wider font-bold transition-opacity"
              style={{
                borderRadius: 6,
                background: agreed
                  ? "linear-gradient(135deg, #4ECCA3, #38b2ac)"
                  : "rgba(78,204,163,0.15)",
                color: agreed ? "#050c18" : "#4ECCA3",
                opacity: agreed ? 1 : 0.4,
                cursor: agreed ? "pointer" : "not-allowed",
              }}
            >
              I Agree
            </button>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}
