// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/pathwise-dashboard/Cockpit.tsx": () => import("../components/mockups/pathwise-dashboard/Cockpit.tsx"),
  "./components/mockups/pathwise-dashboard/Feed.tsx": () => import("../components/mockups/pathwise-dashboard/Feed.tsx"),
  "./components/mockups/pathwise-dashboard/Scorecard.tsx": () => import("../components/mockups/pathwise-dashboard/Scorecard.tsx")
};
