/** All 116 California community colleges for the autocomplete dropdown. */
export const CALIFORNIA_COMMUNITY_COLLEGES = [
  "Allan Hancock College",
  "American River College",
  "Antelope Valley College",
  "Bakersfield College",
  "Barstow Community College",
  "Berkeley City College",
  "Butte College",
  "Cabrillo College",
  "Cañada College",
  "Cerritos College",
  "Cerro Coso Community College",
  "Chabot College",
  "Chaffey College",
  "Citrus College",
  "City College of San Francisco",
  "Clovis Community College",
  "Coastline Community College",
  "College of Alameda",
  "College of Marin",
  "College of San Mateo",
  "College of the Canyons",
  "College of the Desert",
  "College of the Redwoods",
  "College of the Sequoias",
  "College of the Siskiyous",
  "Columbia College",
  "Compton College",
  "Contra Costa College",
  "Copper Mountain College",
  "Cosumnes River College",
  "Crafton Hills College",
  "Cuesta College",
  "Cuyamaca College",
  "Cypress College",
  "De Anza College",
  "Diablo Valley College",
  "East Los Angeles College",
  "El Camino College",
  "Evergreen Valley College",
  "Feather River College",
  "Folsom Lake College",
  "Foothill College",
  "Fresno City College",
  "Fullerton College",
  "Gavilan College",
  "Glendale Community College",
  "Golden West College",
  "Grossmont College",
  "Hartnell College",
  "Imperial Valley College",
  "Irvine Valley College",
  "Lake Tahoe Community College",
  "Laney College",
  "Las Positas College",
  "Lassen Community College",
  "Long Beach City College",
  "Los Angeles City College",
  "Los Angeles Harbor College",
  "Los Angeles Mission College",
  "Los Angeles Pierce College",
  "Los Angeles Southwest College",
  "Los Angeles Trade-Technical College",
  "Los Angeles Valley College",
  "Los Medanos College",
  "Mendocino College",
  "Merced College",
  "Merritt College",
  "MiraCosta College",
  "Mission College",
  "Modesto Junior College",
  "Monterey Peninsula College",
  "Moorpark College",
  "Moreno Valley College",
  "Mt. San Antonio College",
  "Mt. San Jacinto College",
  "Napa Valley College",
  "Norco College",
  "Ohlone College",
  "Orange Coast College",
  "Oxnard College",
  "Palomar College",
  "Palo Verde College",
  "Pasadena City College",
  "Porterville College",
  "Reedley College",
  "Rio Hondo College",
  "Riverside City College",
  "Sacramento City College",
  "Saddleback College",
  "San Bernardino Valley College",
  "San Diego City College",
  "San Diego Mesa College",
  "San Diego Miramar College",
  "San Joaquin Delta College",
  "San Jose City College",
  "Santa Ana College",
  "Santa Barbara City College",
  "Santa Monica College",
  "Santa Rosa Junior College",
  "Santiago Canyon College",
  "Shasta College",
  "Sierra College",
  "Skyline College",
  "Solano Community College",
  "Southwestern College",
  "Taft College",
  "Ventura College",
  "Victor Valley College",
  "West Hills College Coalinga",
  "West Hills College Lemoore",
  "West Los Angeles College",
  "West Valley College",
  "Woodland Community College",
  "Yuba College",
] as const;
