/** Common college majors for the autocomplete dropdown. */
export const COLLEGE_MAJORS = [
  "Accounting",
  "African American Studies",
  "American Studies",
  "Anthropology",
  "Applied Mathematics",
  "Arabic",
  "Architecture",
  "Art History",
  "Art Studio",
  "Asian American Studies",
  "Asian Studies",
  "Astronomy",
  "Astrophysics",
  "Atmospheric Science",
  "Biochemistry",
  "Bioengineering",
  "Biological Sciences",
  "Biology",
  "Biomedical Engineering",
  "Biophysics",
  "Biotechnology",
  "Business Administration",
  "Business Economics",
  "Business Information Systems",
  "Cell Biology",
  "Chemical Engineering",
  "Chemistry",
  "Child Development",
  "Chinese",
  "Chicano and Latino Studies",
  "Civil Engineering",
  "Classical Studies",
  "Cognitive Science",
  "Communication Studies",
  "Communications",
  "Comparative Literature",
  "Computer Engineering",
  "Computer Information Systems",
  "Computer Science",
  "Computer Security",
  "Construction Management",
  "Counseling",
  "Creative Writing",
  "Criminal Justice",
  "Criminology",
  "Dance",
  "Data Science",
  "Dental Hygiene",
  "Design",
  "Dietetics",
  "Digital Media",
  "Earth Sciences",
  "East Asian Studies",
  "Ecology",
  "Economics",
  "Education",
  "Electrical Engineering",
  "Elementary Education",
  "Engineering (General)",
  "Engineering Physics",
  "English",
  "Environmental Engineering",
  "Environmental Science",
  "Environmental Studies",
  "Ethnic Studies",
  "Exercise Science",
  "Family and Human Development",
  "Film and Media Studies",
  "Finance",
  "Food Science",
  "Forensic Science",
  "French",
  "Gender and Sexuality Studies",
  "Genetics",
  "Geography",
  "Geology",
  "Geophysics",
  "German",
  "Gerontology",
  "Global Studies",
  "Graphic Design",
  "Health Administration",
  "Health Education",
  "Health Science",
  "History",
  "Hospitality Management",
  "Human Biology",
  "Human Development",
  "Human Resources",
  "Humanities",
  "Industrial Design",
  "Industrial Engineering",
  "Informatics",
  "Information Science",
  "Information Systems",
  "Information Technology",
  "Interior Architecture",
  "International Business",
  "International Relations",
  "Italian",
  "Japanese",
  "Jewish Studies",
  "Journalism",
  "Kinesiology",
  "Labor Studies",
  "Landscape Architecture",
  "Latin American Studies",
  "Law and Society",
  "Liberal Arts",
  "Linguistics",
  "Management",
  "Marine Biology",
  "Marketing",
  "Materials Science Engineering",
  "Mathematics",
  "Mechanical Engineering",
  "Media Arts",
  "Media Studies",
  "Microbiology",
  "Middle Eastern Studies",
  "Molecular Biology",
  "Music",
  "Music Education",
  "Music Industry",
  "Music Performance",
  "Native American Studies",
  "Natural Sciences",
  "Neuroscience",
  "Nursing",
  "Nutrition",
  "Nutritional Science",
  "Occupational Therapy",
  "Oceanography",
  "Operations Management",
  "Optometry",
  "Organizational Leadership",
  "Peace and Conflict Studies",
  "Pharmaceutical Chemistry",
  "Pharmacology",
  "Philosophy",
  "Photography",
  "Physical Education",
  "Physical Sciences",
  "Physical Therapy",
  "Physics",
  "Physiology",
  "Planetary Science",
  "Political Science",
  "Pre-Dentistry",
  "Pre-Law",
  "Pre-Medicine",
  "Pre-Pharmacy",
  "Pre-Veterinary",
  "Psychology",
  "Public Administration",
  "Public Health",
  "Public Policy",
  "Public Relations",
  "Real Estate",
  "Recreation Management",
  "Religious Studies",
  "Respiratory Therapy",
  "Russian",
  "Social Ecology",
  "Social Sciences",
  "Social Work",
  "Sociology",
  "Software Engineering",
  "Spanish",
  "Special Education",
  "Speech and Hearing Sciences",
  "Sports Management",
  "Statistics",
  "Sustainability",
  "Sustainable Design",
  "Teacher Education",
  "Technical Writing",
  "Theatre",
  "Theatre Arts",
  "Tourism Management",
  "Urban Planning",
  "Urban Studies",
  "Visual Arts",
  "Web Development",
  "Wildlife Biology",
  "Women's Studies",
  "World Arts and Cultures",
  "Zoology",
] as const;
